# Site settings
title: Talks | Red Panthers - Experts in Ruby on Rails kochi, India
email: tech@redpanthers.co
description: "We specialize in helping our clients validate, build and expand their business through technology.
If you have an idea, or want to build something innovative, Let's help you.
"

baseurl: "/slides" # the subpath of your site, e.g. /blog/
url: "http://slides.redpanthers.co" # the base hostname & protocol for your site
twitter_username: redpanthershq
github_username:  redpanthers
linkedin_username: redpanthers
instagram_username: redpanthers

# Build settings
markdown: kramdown

permalink: /:year/:month/:day/:title

gems:
  - octopress-image-tag
  - octopress-video-tag
  - octopress-codeblock
  - octopress-quote-tag
  - octopress-codefence
  - octopress-solarized
  - octopress-gist
